# Part II. Introduction to NumPy

datasets can come from a wide range of sources and in a wide range of formats, including collections of documents, collections of images, collections of sound clips, collections of numerical measurements, or nearly anything else. Despite this apparent heterogeneity, many datasets can be represented fundamentally as arrays of numbers. No matter what the data is, the first step in making it analyzable will be to transform it into arrays of numbers.

In [5]:
import numpy

In [8]:
numpy.__version__

'2.3.5'

In [10]:
import numpy as np

In [11]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Users\\rajan\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>
File:        c:\users\rajan\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>>

In [2]:
#Python allows dynamic typing, unlike C or C++ which are statically types, thereby not allowing the following operation
x = 4
print(x,type(x))
x = "Four"
print(x,type(x))

4 <class 'int'>
Four <class 'str'>


In [13]:
L = list(range(10))
print(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [18]:
L2 = [str(element) for element in L]
print(L2)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [23]:
print(type(L))
print(type(L2))
print(type(L[0]))
print(type(L2[0]))

<class 'list'>
<class 'list'>
<class 'int'>
<class 'str'>


In [25]:
# Because of Python’s dynamic typing, we can even create heterogeneous lists
L3 = [True, 1, 1.0,"One"]
[type(item) for item in L3]

[bool, int, float, str]

At the implementation level, the array essentially contains a single pointer to one contiguous block of data. The Python list, on the other hand, contains a pointer to a block of pointers, each of which in turn points to a full Python object like the Python integer we saw earlier. Again, the advantage of the list is flexibility: because each list element is a full structure containing both data and type information, the list can be filled with data of any desired type. Fixed-type NumPy-style arrays lack this flexibility, but are much more efficient for storing and manipulating data.

In [27]:
import array
L = list(range(10))
A = array.array("i",L)      #Here, 'i' is a type code indicating the contents are integers.
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
import numpy as np

In [30]:
#we can use np.array to create arrays from Python lists
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

NumPy arrays can only contain data of the same type. If the types do not match, NumPy will upcast them according to its type promotion rules; here, integers are upcast to floating point

In [31]:
np.array([3.14,1,4,3,2])

array([3.14, 1.  , 4.  , 3.  , 2.  ])

If we want to explicitly set the data type of the resulting array, we can use the dtype keyword

In [2]:
np.array([1,2,3,4], dtype = np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [5]:
y = np.array([5,6,78.78,8],dtype = float)
print(y)
y

[ 5.    6.   78.78  8.  ]


array([ 5.  ,  6.  , 78.78,  8.  ])

In [6]:
type(y)

numpy.ndarray

In [43]:
#Python elements of lists
for i in [2,4,6]:
    print(list(range(i,i+3)))

[2, 3, 4]
[4, 5, 6]
[6, 7, 8]


In [44]:
#Python lists of lists
L = []
for i in [2,4,6]:
    L.append(list(range(i,i+3)))
print(L)

[[2, 3, 4], [4, 5, 6], [6, 7, 8]]


In [65]:
#numpy arrays
rows = []
for i in [2,4,6]:
    rows.append(range(i,i+3))
print(rows)
np.array(rows)

[range(2, 5), range(4, 7), range(6, 9)]


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [51]:
#numpy arrays - condensed version using list comprehensions
x = np.array([range(i,i+3) for i in [2,4,6]])
x

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [52]:
type(x)

numpy.ndarray

In [55]:
x.shape #3x3 matrix

(3, 3)

### Creating arrays from scratch

In [57]:
# Create a length-10 integer array filled with 0s
x = np.zeros(10,dtype = int)
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
# Create a 3x5 floating-point array filled with 0s
np.zeros((2,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [63]:
# Create a 3x5 floating-point array filled with 1s
y = np.ones((3,5),dtype = float)
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])