# Part II. Introduction to NumPy

datasets can come from a wide range of sources and in a wide range of formats, including collections of documents, collections of images, collections of sound clips, collections of numerical measurements, or nearly anything else. Despite this apparent heterogeneity, many datasets can be represented fundamentally as arrays of numbers. No matter what the data is, the first step in making it analyzable will be to transform it into arrays of numbers.

###### numpy = NUMerical PYthon

In [3]:

import numpy

In [6]:
numpy.__version__

'2.4.6'

In [7]:
#importing as alias

import numpy as np

In [8]:
np?

Type:        module
String form: <module 'numpy' from '/home/rajan/miniforge3/envs/python_ds_handbook/lib/python3.14/site-packages/numpy/__init__.py'>
File:        ~/miniforge3/envs/python_ds_handbook/lib/python3.14/site-packages/numpy/__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated 

### Data types in python

In [ ]:
/* C code */
int result = 0;
for(int i=0; i<100; i++){
    result += i;
}

In [ ]:
# Python code
result = 0
for i in range(100):
    result += i

Unlike in C, in Python there is no need to name the data type of the variable. 

 a C integer is essentially a label for a position in memory whose bytes encode an integer value. A Python integer is a pointer to a position in memory containing all the Python object information, including the bytes that contain the integer value. 

In [9]:
L1 = list(range(10))
L2 = [str(x) for x in L1]

print(L1)
print(L2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [11]:
L3 = [True, 120, 3.14,"alpha" ]
[type(c) for c in L3]

[bool, int, float, str]

: to allow these flexible types, each item in the list must contain its own type, reference count, and other information. That is, each item is a complete Python object.

### Fixed type arrays in Python

In [12]:
import array
L = list(range(10))
A = array.array("i",L)
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


'i' is a type code indicating the contents are integers.

### Creating numpy arrays from python lists

In [13]:
import numpy as np

In [14]:
np.array([1,2,3,5,7,8,24])

array([ 1,  2,  3,  5,  7,  8, 24])

Unlike python lists, numpy array can only contain data of the same type. If the elements differ in type, numpy will type cast them according to promotion rules

In [17]:
np.array([3.14,2,5,7,8])  #Integers got type castsed to float due to the 3.14

array([3.14, 2.  , 5.  , 7.  , 8.  ])

In [19]:
np.array([1,2,3,4],dtype = np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [20]:
np.array([1,2,3,4],dtype = np.float64)

array([1., 2., 3., 4.])

In [22]:
#Multi dimensional array
np.array([range(i,i+2) for i in [2,4,6]])

array([[2, 3],
       [4, 5],
       [6, 7]])

In [23]:
#Multi dimensional array
np.array([range(i,i+4) for i in [2,4,6]])

array([[2, 3, 4, 5],
       [4, 5, 6, 7],
       [6, 7, 8, 9]])

In [1]:
import numpy as np
np.array([i for i in range(0,10,3)])

array([0, 3, 6, 9])

### Creating Arrays from Scratch

In [24]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

zeros keyword creates numpy arrays filled with just 0s. 
Similarly, ones keyword creates arrays with just 1s. 
Using broadcasting ahnd other scalar multiplications, these 1s and 0s can later be manipulated 

In [26]:
np.ones(2,dtype = int)

array([1, 1])

In [27]:
np.ones((2,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
np.ones((2,5,3), dtype = int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [29]:
np.ones((2,5,3,4), dtype = int)

array([[[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]],


       [[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]]])

In [30]:
np.full((3,5), 3.14,)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [33]:
np.arange(0,20,3)  #Behaves ;ilke range(start,stop,step) function in python

array([ 0,  3,  6,  9, 12, 15, 18])

In [38]:
np.linspace(20,40,5) #Return evenly spaced numbers over a specified interval.

array([20., 25., 30., 35., 40.])

In [37]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [42]:
np.random.random((3,3)) #Creates a 3x3 matrix of random values between 0 and 1

array([[0.07212967, 0.5553557 , 0.67105304],
       [0.47067458, 0.97631466, 0.99989739],
       [0.19195262, 0.36549265, 0.38352979]])

In [48]:
np.random.normal(0,1,(3,3)) 
#Creates a 3x3 matrix of normally distributed 
#random values with mean 0 and standard deviation 1

array([[-2.43196433, -0.92517547,  0.02839029],
       [-1.89529549, -0.45130143, -0.24329128],
       [ 0.00963376, -0.40948661,  0.41195664]])

In [51]:
np.random.randint(6,34,(3,5))
#Creates a 3x5 matrix of random values >= 6 and < 34

array([[20, 33, 18, 16, 30],
       [ 6,  8,  9, 29, 25],
       [30, 32, 31, 17,  7]])

In [53]:
np.eye(4)  
#Creates a 4x4 identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.empty(4)

array([1., 1., 1., 1.])

In [5]:
np.zeros(10, dtype = "int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [6]:
np.zeros(10,dtype = np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

#### Numpy standard data types

Data type	Description

bool_

Boolean (True or False) stored as a byte

int_

Default integer type (same as C long; normally either int64 or int32)

intc

Identical to C int (normally int32 or int64)

intp

Integer used for indexing (same as C ssize_t; normally either int32 or int64)

int8

Byte (–128 to 127)

int16

Integer (–32768 to 32767)

int32

Integer (–2147483648 to 2147483647)

int64

Integer (–9223372036854775808 to 9223372036854775807)

uint8

Unsigned integer (0 to 255)

uint16

Unsigned integer (0 to 65535)

uint32

Unsigned integer (0 to 4294967295)

uint64

Unsigned integer (0 to 18446744073709551615)

float_

Shorthand for float64

float16

Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa

float32

Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa

float64

Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa

complex_

Shorthand for complex128

complex64

Complex number, represented by two 32-bit floats

complex128

Complex number, represented by two 64-bit floats

## Chapter 5 - Basics of Numpy arrays

### Numpy array attributes



DEfine random raays of 1, 2 and 3 dimensions. 

In [7]:
import numpy as np

rng = np.random.default_rng(seed = 1000)

x1 = rng.integers(10,size = 6)      # 1D array
x2 = rng.integers(10, size = (3,4)) # 2D array
x3 = rng.integers(10, size = (3,4,5)) #3D array

Each array has attributes: `ndim` (no. pf dimensions); `shape` (size of each dimension); `size` (total size of the array) and `dtype` (the type of each array element)

In [10]:
print(x1)
print("__________________________________")
print(x2)
print("__________________________________")
print(x3)

[2 5 8 6 8 4]
__________________________________
[[2 2 5 5]
 [2 1 4 2]
 [2 7 1 5]]
__________________________________
[[[0 8 8 8 6]
  [2 7 1 6 9]
  [1 6 1 2 4]
  [2 9 6 8 6]]

 [[3 8 4 9 8]
  [1 6 6 8 4]
  [3 0 8 2 9]
  [3 7 3 1 9]]

 [[0 7 1 1 2]
  [3 6 8 9 1]
  [8 0 1 3 4]
  [4 7 8 5 0]]]
